
spring:
  cloud:
    gateway:
      routes:
        - id: replicator
          uri: lb://replicator
          predicates:
            - Method=GET
          filters:
            - StripPrefix=1
  application:
    name: gateway
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
